@CadastrosMateriais_HostAddress = http://localhost:5008

GET {{CadastrosMateriais_HostAddress}}/weatherforecast/
Accept: application/json

###
{
    "id":,
    "nome": "Material Teste",
    "descricao": "Descrição do Material Teste",
    "quantidade": 10
}

